-- CreateTable
CREATE TABLE "pokemons" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "pokedex_number" INTEGER NOT NULL,
    "img_name" JSONB NOT NULL,
    "generation" INTEGER NOT NULL,
    "evolution_stage" JSONB,
    "evolved" INTEGER NOT NULL,
    "familyid" INTEGER,
    "cross_gen" INTEGER NOT NULL,
    "type_1" TEXT NOT NULL,
    "type_2" TEXT,
    "weather_1" TEXT NOT NULL,
    "weather_2" TEXT,
    "stat_total" INTEGER NOT NULL,
    "atk" INTEGER NOT NULL,
    "def" INTEGER NOT NULL,
    "sta" INTEGER NOT NULL,
    "legendary" INTEGER NOT NULL,
    "aquireable" INTEGER NOT NULL,
    "spawns" INTEGER NOT NULL,
    "regional" INTEGER NOT NULL,
    "raidable" INTEGER NOT NULL,
    "hatchable" INTEGER NOT NULL,
    "shiny" INTEGER NOT NULL,
    "nest" INTEGER NOT NULL,
    "new" INTEGER NOT NULL,
    "not_gettable" INTEGER NOT NULL,
    "future_evolve" INTEGER NOT NULL,
    "cp_40" INTEGER NOT NULL,
    "cp_39" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "pokemons_pkey" PRIMARY KEY ("id")
);
